version="0.3.2"

[scripts]
build-tailwind-dev = "npx tailwindcss -c ./tailwind.config.js -o ./tailwind.css"

build-tailwind-prod = "NODE_ENV=production npx tailwindcss -c ./tailwind.config.js -o ./tailwind.css --minify"

setup.subcommands.tailwind = "bonnie build-tailwind-dev"
setup.subcommands.prompt-tailwind = "echo \"Have you installed the Tailwind CLI globally with 'npm i -g tailwindcss' or 'yarn global add tailwindcss'?\""
setup.order = """
tailwind {
  Failure => prompt-tailwind
}
"""

run.cmd = "trunk serve"

run.subcommands.proxy = "trunk serve --proxy-backend=https://yew.rs/tutorial"

build.cmd = [
  "bonnie build-tailwind-dev",
  "trunk build",
  "cp netlify.toml dist/"
]

build.subcommands.release = [
  "bonnie build-tailwind-prod",
  "trunk build --release",
  "cp netlify.toml dist/"
]
